name: Composer Normalize

on: [push, pull_request]

permissions:
  contents: read

jobs:
  composer-normalize:
    name: Composer Normalize (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.5']

    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug

      - name: Composer install
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4

      - name: Check composer.json is normalized
        run: composer normalize --dry-run
