name: Pest tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pest_phpstand:
    name: Pest tests (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.5']

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug

      - name: Composer install
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4

      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
          php artisan config:clear
          php artisan migrate -v

      - name: Run Pest Tests
        run: php -d memory_limit=-1 vendor/bin/pest
